parse:
  additional_commands:
    add_mp_units_module:
      pargs:
        nargs: 2
      kwargs:
        DEPENDENCIES: "+"
        HEADERS: "*"
        MODULE_INTERFACE_UNIT: "?"
    enable_iwyu:
      pargs:
        flags:
          - NO_FORWARD_DECLARATIONS
          - QUOTED_INCLUDES_FIRST
          - NO_COMMENTS
      kwargs:
        MAPPING_FILE: 1
        MAX_LINE_LENGTH: 1
format:
  line_width: 120
  tab_size: 4
  max_subgroups_hwrap: 3
  max_pargs_hwrap: 6
  max_rows_cmdline: 2
  dangle_parens: true
  min_prefix_chars: 8
  max_prefix_chars: 8
  max_lines_hwrap: 2
markup:
  enable_markup: false
